name: Update Blog Posts

on:
  schedule:
    - cron: "30 */6 * * *"  # alle 6 Stunden
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: gautamkrishnar/blog-post-workflow@v1
        with:
          # SETZE HIER DEIN RSS FEED EIN (z.B. dev.to / medium / eigener blog)
          feed_list: "https://dev.to/feed/sargisheiser"

